apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGODB_USERNAME: {{ .Values.mongodb.username | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc | quote }}
